global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'my_application'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['172.29.171.239:5200']  # Replace with your app's hostname/IP
